In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [8]:
data = pd.read_csv('subconjunto.csv')
data

,cole_depto_ubicacion,cole_mcpio_ubicacion,estu_depto_presentacion,estu_depto_reside,fami_estratovivienda,fami_tienecomputador,fami_tieneinternet,punt_global
0,SANTANDER,EL CARMEN DE CHUCURÍ,SANTANDER,SANTANDER,Estrato 1,No,No,NaN
1,SANTANDER,BUCARAMANGA,SANTANDER,SANTANDER,NaN,Si,Si,NaN
2,SANTANDER,BARRANCABERMEJA,SANTANDER,SANTANDER,Estrato 1,No,No,203.0
3,SANTANDER,CAPITANEJO,SANTANDER,SANTANDER,Estrato 1,No,No,153.0
4,SANTANDER,SABANA DE TORRES,SANTANDER,SANTANDER,NaN,NaN,NaN,176.0
...,...,...,...,...,...,...,...,...
339768,SANTANDER,FLORIDABLANCA,SANTANDER,SANTANDER,Estrato 3,No,Si,212.0
339769,SANTANDER,SAN GIL,SANTANDER,SANTANDER,Estrato 2,Si,Si,289.0
339770,SANTANDER,PIEDECUESTA,SANTANDER,SANTANDER,Estrato 2,Si,Si,238.0
339771,SANTANDER,SABANA DE TORRES,SANTANDER,SANTANDER,Estrato 1,No,No,198.0
339772,SANTANDER,COROMORO,SANTANDER,SANTANDER,Estrato 1,No,No,257.0

In [10]:
(data.isna().sum())/len(data) *100

cole_depto_ubicacion        0.000000
cole_mcpio_ubicacion        0.000000
estu_depto_presentacion     0.000000
estu_depto_reside           0.000000
fami_estratovivienda        2.054901
fami_tienecomputador        2.129657
fami_tieneinternet          1.890968
punt_global                39.174684
dtype: float64

In [12]:
data_limpia =pd.read_csv('saber11_santander_limpio.csv')
data_limpia

,cole_depto_ubicacion,cole_mcpio_ubicacion,estu_depto_presentacion,estu_depto_reside,fami_estratovivienda,fami_tienecomputador,fami_tieneinternet,punt_global
0,SANTANDER,BARRANCABERMEJA,SANTANDER,SANTANDER,Estrato 1,No,No,203.0
1,SANTANDER,CAPITANEJO,SANTANDER,SANTANDER,Estrato 1,No,No,153.0
2,SANTANDER,SABANA DE TORRES,SANTANDER,SANTANDER,NO REPORTA,NO REPORTA,NO REPORTA,176.0
3,SANTANDER,SABANA DE TORRES,SANTANDER,SANTANDER,NO REPORTA,NO REPORTA,NO REPORTA,176.0
4,SANTANDER,OIBA,SANTANDER,SANTANDER,Estrato 2,Si,Si,254.0
...,...,...,...,...,...,...,...,...
206663,SANTANDER,FLORIDABLANCA,SANTANDER,SANTANDER,Estrato 3,No,Si,212.0
206664,SANTANDER,SAN GIL,SANTANDER,SANTANDER,Estrato 2,Si,Si,289.0
206665,SANTANDER,PIEDECUESTA,SANTANDER,SANTANDER,Estrato 2,Si,Si,238.0
206666,SANTANDER,SABANA DE TORRES,SANTANDER,SANTANDER,Estrato 1,No,No,198.0
206667,SANTANDER,COROMORO,SANTANDER,SANTANDER,Estrato 1,No,No,257.0

In [13]:
((data_limpia =='NO REPORTA').sum())/len(data_limpia) *100

cole_depto_ubicacion       0.000000
cole_mcpio_ubicacion       0.000000
estu_depto_presentacion    0.000000
estu_depto_reside          0.000000
fami_estratovivienda       3.217237
fami_tienecomputador       1.825150
fami_tieneinternet         2.858691
punt_global                0.000000
dtype: float64