In [10]:
import pandas as pd
import numpy as np
import unicodedata

In [ ]:
df = pd.read_csv("C:/Users/pinil/Proyecto_1/Subconjunto_FINAL_datos.csv")

In [9]:
df.info()
df.isna().sum()

<class 'pandas.DataFrame'>
RangeIndex: 339773 entries, 0 to 339772
Data columns (total 19 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   cole_depto_ubicacion      339773 non-null  str
 1   cole_mcpio_ubicacion      339773 non-null  str
 2   cole_area_ubicacion       339742 non-null  str
 3   cole_naturaleza           339773 non-null  str
 4   estu_depto_presentacion   339773 non-null  str
 5   estu_depto_reside         339773 non-null  str
 6   fami_tienecomputador      332537 non-null  str
 7   fami_tieneinternet        333348 non-null  str
 8   fami_cuartoshogar         335406 non-null  str
 9   fami_educacionmadre       330683 non-null  str
 10  fami_educacionpadre       330675 non-null  str
 11  fami_personashogar        335548 non-null  str
 12  fami_estratovivienda      332791 non-null  str
 13  punt_matematicas          339773 non-null  float64
 14  punt_lectura_critica      206668 non-null  float64
 15  punt_ingles               339772 non-null  float64
 16  punt_c_naturales          206668 non-null  float64
 17  punt_sociales_ciudadanas  206668 non-null  float64
 18  punt_global               206668 non-null  float64
dtypes: float64(6), str(13)
memory usage: 49.3 MB

cole_depto_ubicacion             0
cole_mcpio_ubicacion             0
cole_area_ubicacion             31
cole_naturaleza                  0
estu_depto_presentacion          0
estu_depto_reside                0
fami_tienecomputador          7236
fami_tieneinternet            6425
fami_cuartoshogar             4367
fami_educacionmadre           9090
fami_educacionpadre           9098
fami_personashogar            4225
fami_estratovivienda          6982
punt_matematicas                 0
punt_lectura_critica        133105
punt_ingles                      1
punt_c_naturales            133105
punt_sociales_ciudadanas    133105
punt_global                 133105
dtype: int64

Se identifico que alguno datos tiene tildes, por ende se eliminaron las tildes

In [8]:
def quitar_tildes(texto):
    if isinstance(texto, str):
        texto = unicodedata.normalize('NFKD', texto)
        texto = texto.encode('ascii', 'ignore').decode('utf-8')
    return texto

In [11]:
cols_texto = df.select_dtypes(include="object").columns

df[cols_texto] = df[cols_texto].apply(
    lambda col: col.map(quitar_tildes)
)

C:\Users\pinil\AppData\Local\Temp\ipykernel_33292\1542681349.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cols_texto = df.select_dtypes(include="object").columns

Filtrado General

In [12]:
df = df.dropna(subset=["punt_global"])

In [ ]:
df.isna().sum()

cole_depto_ubicacion           0
cole_mcpio_ubicacion           0
cole_area_ubicacion            0
cole_naturaleza                0
estu_depto_presentacion        0
estu_depto_reside              0
fami_tienecomputador        3772
fami_tieneinternet          5908
fami_cuartoshogar           3880
fami_educacionmadre         5768
fami_educacionpadre         5774
fami_personashogar          3714
fami_estratovivienda        6649
punt_matematicas               0
punt_lectura_critica           0
punt_ingles                    1
punt_c_naturales               0
punt_sociales_ciudadanas       0
punt_global                    0
dtype: int64

Filtrado para pregunta 1

In [14]:
df1=df.dropna(subset=["fami_cuartoshogar",
              "fami_educacionmadre",
              "fami_educacionpadre",
              "fami_personashogar",
              "fami_estratovivienda"
              ])

In [15]:
df1.isna().sum()

cole_depto_ubicacion          0
cole_mcpio_ubicacion          0
cole_area_ubicacion           0
cole_naturaleza               0
estu_depto_presentacion       0
estu_depto_reside             0
fami_tienecomputador        303
fami_tieneinternet          285
fami_cuartoshogar             0
fami_educacionmadre           0
fami_educacionpadre           0
fami_personashogar            0
fami_estratovivienda          0
punt_matematicas              0
punt_lectura_critica          0
punt_ingles                   1
punt_c_naturales              0
punt_sociales_ciudadanas      0
punt_global                   0
dtype: int64

In [16]:
df1 = df1.drop(columns=[
    'punt_matematicas',
    'punt_lectura_critica',
    'punt_ingles',
    'punt_c_naturales',
    'punt_sociales_ciudadanas',
    "cole_naturaleza",
    "cole_area_ubicacion",
    "fami_tienecomputador",
    "fami_tieneinternet"
])

In [17]:
df1["fami_personashogar"].unique()

<StringArray>
[    'Cuatro',      '5 a 6', 'Doce o mas',      '3 a 4',      '1 a 2',
       'Tres',      'Cinco',       'Ocho',       'Seis',    '9 o mas',
      '7 a 8',      'Siete',        'Dos',      'Nueve',        'Una',
       'Once',       'Diez']
Length: 17, dtype: str

In [18]:
df1["fami_cuartoshogar"].unique()

<StringArray>
[      'Tres',        'Dos',     'Cuatro',       'Seis',        'Uno',
       'Ocho',      'Cinco',      'Siete', 'Seis o mas',      'Nueve',
 'Diez o mas']
Length: 11, dtype: str

In [19]:
df1

,cole_depto_ubicacion,cole_mcpio_ubicacion,estu_depto_presentacion,estu_depto_reside,fami_cuartoshogar,fami_educacionmadre,fami_educacionpadre,fami_personashogar,fami_estratovivienda,punt_global
0,SANTANDER,VELEZ,SANTANDER,SANTANDER,Tres,Secundaria (Bachillerato) incompleta,Secundaria (Bachillerato) completa,Cuatro,Estrato 1,167.0
2,SANTANDER,CAPITANEJO,SANTANDER,SANTANDER,Dos,Tecnica o tecnologica completa,Primaria incompleta,Cuatro,Estrato 2,333.0
3,SANTANDER,BUCARAMANGA,SANTANDER,SANTANDER,Tres,Tecnica o tecnologica incompleta,Secundaria (Bachillerato) incompleta,5 a 6,Estrato 1,314.0
4,SANTANDER,BUCARAMANGA,SANTANDER,SANTANDER,Tres,Tecnica o tecnologica incompleta,Secundaria (Bachillerato) incompleta,5 a 6,Estrato 1,314.0
7,SANTANDER,BUCARAMANGA,SANTANDER,SANTANDER,Cuatro,Secundaria (Bachillerato) incompleta,Secundaria (Bachillerato) incompleta,Cuatro,Estrato 3,295.0
...,...,...,...,...,...,...,...,...,...,...
339766,SANTANDER,SUCRE,SANTANDER,SANTANDER,Cuatro,Primaria completa,Primaria completa,Cinco,Estrato 1,274.0
339767,SANTANDER,FLORIDABLANCA,SANTANDER,SANTANDER,Tres,Secundaria (Bachillerato) completa,Secundaria (Bachillerato) incompleta,3 a 4,Estrato 2,240.0
339768,SANTANDER,FLORIDABLANCA,SANTANDER,SANTANDER,Tres,Secundaria (Bachillerato) completa,Secundaria (Bachillerato) incompleta,3 a 4,Estrato 2,240.0
339769,SANTANDER,BUCARAMANGA,SANTANDER,SANTANDER,Cuatro,Tecnica o tecnologica completa,Educacion profesional completa,3 a 4,Estrato 2,337.0
339770,SANTANDER,BUCARAMANGA,SANTANDER,SANTANDER,Cuatro,Tecnica o tecnologica completa,Educacion profesional completa,3 a 4,Estrato 2,337.0

In [20]:
df1.to_csv("C:/Users/pinil/OneDrive/Escritorio/Analitica computacional/Proyecto//saber11_pregunta_1.csv", index=False)

Filtrado para pregunta 2

In [21]:
df2=df.dropna(subset=["punt_ingles",
              ])

In [22]:
df2.isna().sum()

cole_depto_ubicacion           0
cole_mcpio_ubicacion           0
cole_area_ubicacion            0
cole_naturaleza                0
estu_depto_presentacion        0
estu_depto_reside              0
fami_tienecomputador        3772
fami_tieneinternet          5908
fami_cuartoshogar           3880
fami_educacionmadre         5768
fami_educacionpadre         5774
fami_personashogar          3714
fami_estratovivienda        6649
punt_matematicas               0
punt_lectura_critica           0
punt_ingles                    0
punt_c_naturales               0
punt_sociales_ciudadanas       0
punt_global                    0
dtype: int64

In [23]:
df2 = df2.drop(columns=[
    "fami_cuartoshogar",
    "fami_educacionmadre",
    "fami_educacionpadre",
    "fami_personashogar",
    "fami_estratovivienda",
    "fami_tienecomputador",
    "fami_tieneinternet"
])

In [24]:
df2

,cole_depto_ubicacion,cole_mcpio_ubicacion,cole_area_ubicacion,cole_naturaleza,estu_depto_presentacion,estu_depto_reside,punt_matematicas,punt_lectura_critica,punt_ingles,punt_c_naturales,punt_sociales_ciudadanas,punt_global
0,SANTANDER,VELEZ,URBANO,NO OFICIAL,SANTANDER,SANTANDER,33.0,23.0,45.0,36.0,38.0,167.0
2,SANTANDER,CAPITANEJO,URBANO,OFICIAL,SANTANDER,SANTANDER,83.0,59.0,52.0,69.0,60.0,333.0
3,SANTANDER,BUCARAMANGA,URBANO,OFICIAL,SANTANDER,SANTANDER,65.0,59.0,60.0,63.0,65.0,314.0
4,SANTANDER,BUCARAMANGA,URBANO,OFICIAL,SANTANDER,SANTANDER,65.0,59.0,60.0,63.0,65.0,314.0
7,SANTANDER,BUCARAMANGA,URBANO,OFICIAL,SANTANDER,SANTANDER,50.0,63.0,55.0,61.0,63.0,295.0
...,...,...,...,...,...,...,...,...,...,...,...,...
339766,SANTANDER,SUCRE,URBANO,OFICIAL,SANTANDER,SANTANDER,58.0,57.0,55.0,54.0,50.0,274.0
339767,SANTANDER,FLORIDABLANCA,URBANO,OFICIAL,SANTANDER,SANTANDER,54.0,44.0,49.0,50.0,44.0,240.0
339768,SANTANDER,FLORIDABLANCA,URBANO,OFICIAL,SANTANDER,SANTANDER,54.0,44.0,49.0,50.0,44.0,240.0
339769,SANTANDER,BUCARAMANGA,URBANO,OFICIAL,SANTANDER,SANTANDER,67.0,66.0,74.0,68.0,66.0,337.0
339770,SANTANDER,BUCARAMANGA,URBANO,OFICIAL,SANTANDER,SANTANDER,67.0,66.0,74.0,68.0,66.0,337.0

In [25]:
df2.to_csv("C:/Users/pinil/OneDrive/Escritorio/Analitica computacional/Proyecto//saber11_pregunta_2.csv", index=False)

Filtrado para pregunta 3

In [26]:
df3=df.dropna(subset=["punt_ingles",
                      "fami_tienecomputador",
                      "fami_tieneinternet"
              ])

In [27]:
df3.isna().sum()

cole_depto_ubicacion           0
cole_mcpio_ubicacion           0
cole_area_ubicacion            0
cole_naturaleza                0
estu_depto_presentacion        0
estu_depto_reside              0
fami_tienecomputador           0
fami_tieneinternet             0
fami_cuartoshogar            455
fami_educacionmadre          253
fami_educacionpadre          340
fami_personashogar           317
fami_estratovivienda        1022
punt_matematicas               0
punt_lectura_critica           0
punt_ingles                    0
punt_c_naturales               0
punt_sociales_ciudadanas       0
punt_global                    0
dtype: int64

In [28]:
df3 = df3.drop(columns=[
    'fami_cuartoshogar',
    'fami_educacionmadre',
    'fami_educacionpadre',
    'fami_personashogar',
    'fami_estratovivienda',
    "cole_naturaleza",
    "cole_area_ubicacion"
])

In [29]:
df3

,cole_depto_ubicacion,cole_mcpio_ubicacion,estu_depto_presentacion,estu_depto_reside,fami_tienecomputador,fami_tieneinternet,punt_matematicas,punt_lectura_critica,punt_ingles,punt_c_naturales,punt_sociales_ciudadanas,punt_global
0,SANTANDER,VELEZ,SANTANDER,SANTANDER,Si,No,33.0,23.0,45.0,36.0,38.0,167.0
2,SANTANDER,CAPITANEJO,SANTANDER,SANTANDER,Si,No,83.0,59.0,52.0,69.0,60.0,333.0
3,SANTANDER,BUCARAMANGA,SANTANDER,SANTANDER,Si,Si,65.0,59.0,60.0,63.0,65.0,314.0
4,SANTANDER,BUCARAMANGA,SANTANDER,SANTANDER,Si,Si,65.0,59.0,60.0,63.0,65.0,314.0
7,SANTANDER,BUCARAMANGA,SANTANDER,SANTANDER,No,No,50.0,63.0,55.0,61.0,63.0,295.0
...,...,...,...,...,...,...,...,...,...,...,...,...
339766,SANTANDER,SUCRE,SANTANDER,SANTANDER,No,No,58.0,57.0,55.0,54.0,50.0,274.0
339767,SANTANDER,FLORIDABLANCA,SANTANDER,SANTANDER,Si,Si,54.0,44.0,49.0,50.0,44.0,240.0
339768,SANTANDER,FLORIDABLANCA,SANTANDER,SANTANDER,Si,Si,54.0,44.0,49.0,50.0,44.0,240.0
339769,SANTANDER,BUCARAMANGA,SANTANDER,SANTANDER,Si,Si,67.0,66.0,74.0,68.0,66.0,337.0
339770,SANTANDER,BUCARAMANGA,SANTANDER,SANTANDER,Si,Si,67.0,66.0,74.0,68.0,66.0,337.0

In [30]:
df3.isna().sum()

cole_depto_ubicacion        0
cole_mcpio_ubicacion        0
estu_depto_presentacion     0
estu_depto_reside           0
fami_tienecomputador        0
fami_tieneinternet          0
punt_matematicas            0
punt_lectura_critica        0
punt_ingles                 0
punt_c_naturales            0
punt_sociales_ciudadanas    0
punt_global                 0
dtype: int64

In [31]:
df3["grupo_tec"] = np.select(
    [
        (df3["fami_tienecomputador"]=="No") & (df3["fami_tieneinternet"]=="No"),
        (df3["fami_tienecomputador"]=="Si") & (df3["fami_tieneinternet"]=="No"),
        (df3["fami_tienecomputador"]=="No") & (df3["fami_tieneinternet"]=="Si"),
        (df3["fami_tienecomputador"]=="Si") & (df3["fami_tieneinternet"]=="Si")
    ],
    [
        "Sin acceso",
        "Solo computador",
        "Solo internet",
        "Computador + internet"
    ],
    default="Otro"
)

In [32]:
df3

,cole_depto_ubicacion,cole_mcpio_ubicacion,estu_depto_presentacion,estu_depto_reside,fami_tienecomputador,fami_tieneinternet,punt_matematicas,punt_lectura_critica,punt_ingles,punt_c_naturales,punt_sociales_ciudadanas,punt_global,grupo_tec
0,SANTANDER,VELEZ,SANTANDER,SANTANDER,Si,No,33.0,23.0,45.0,36.0,38.0,167.0,Solo computador
2,SANTANDER,CAPITANEJO,SANTANDER,SANTANDER,Si,No,83.0,59.0,52.0,69.0,60.0,333.0,Solo computador
3,SANTANDER,BUCARAMANGA,SANTANDER,SANTANDER,Si,Si,65.0,59.0,60.0,63.0,65.0,314.0,Computador + internet
4,SANTANDER,BUCARAMANGA,SANTANDER,SANTANDER,Si,Si,65.0,59.0,60.0,63.0,65.0,314.0,Computador + internet
7,SANTANDER,BUCARAMANGA,SANTANDER,SANTANDER,No,No,50.0,63.0,55.0,61.0,63.0,295.0,Sin acceso
...,...,...,...,...,...,...,...,...,...,...,...,...,...
339766,SANTANDER,SUCRE,SANTANDER,SANTANDER,No,No,58.0,57.0,55.0,54.0,50.0,274.0,Sin acceso
339767,SANTANDER,FLORIDABLANCA,SANTANDER,SANTANDER,Si,Si,54.0,44.0,49.0,50.0,44.0,240.0,Computador + internet
339768,SANTANDER,FLORIDABLANCA,SANTANDER,SANTANDER,Si,Si,54.0,44.0,49.0,50.0,44.0,240.0,Computador + internet
339769,SANTANDER,BUCARAMANGA,SANTANDER,SANTANDER,Si,Si,67.0,66.0,74.0,68.0,66.0,337.0,Computador + internet
339770,SANTANDER,BUCARAMANGA,SANTANDER,SANTANDER,Si,Si,67.0,66.0,74.0,68.0,66.0,337.0,Computador + internet

In [33]:
df3.to_csv("C:/Users/pinil/OneDrive/Escritorio/Analitica computacional/Proyecto//saber11_pregunta_3.csv", index=False)